export const endpoints = {
  books: "/books",
  customers: "/customers",
  customerContacts: "/customer-contacts",
  exportBooks: "books/export",
  getBookBySku: (sku: string) => `/books/sku/${sku}`,
  inventoryTransactions: "/inventory-transactions",
  locations: "/book-stock-locations",
  paymentReceived: "/payment-received",
  paymentMade: "/payment-made",
  purchaseOrders: "/purchase-orders",
  roles: "/roles",
  saleOrders: "/sale-orders",
  shipments: "/shipments",
  shipmentMethods: "/shipment-methods",
  suppliers: "/suppliers",
  uploadBooks: "/books/upload",
  uploadImage: "/upload/image",
  users: "/users",
  warehouses: "/warehouses",
};
